---
- hosts: 192.168.56.2
  tasks:
   - name: wget
     yum: name=wget state=present
   - name: java
     yum: name=java state=present
   - name: repository
     command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
   - name: key
     rpm_key:
       key:  https://jenkins-ci.org/redhat/jenkins-ci.org.key
   - name: jenkins
     yum: name=jenkins state=present
